"""agrego correo electronico a usuario

Revision ID: 260017f035ff
Revises: dff9b356b45f
Create Date: 2026-10-02 19:44:12.987835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel





# revision identifiers, used by Alembic.
revision: str = '260017f035ff'
down_revision: Union[str, Sequence[str], None] = 'dff9b356b45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo_electronico', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('correo_electronico')

    # ### end Alembic commands ###
